CELForum/CELForum/Models/Search/SearchResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CELForum.Models
{
    public class SearchResultModel
    {
        public IEnumerable<PostListingModel> Posts { get; set; }
        public string SearchQuery { get; set; }
        public bool EmptySearchResults { get; set; }
    }
}

CELForum/CELForum/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CELForum.Data;
using CELForum.Data.Models;
using CELForum.Models;
using Microsoft.AspNetCore.Mvc;

namespace CELForum.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;
        public ForumController(IForum forumService, IPost postService)
        {
            _forumService = forumService;
            _postService = postService;
        }

        public IActionResult Index()
        {
            IEnumerable<ForumListingModel> forums = _forumService.GetAll().Select(forum => new ForumListingModel {
                Id = forum.Id,
                Name = forum.Title,
                Description = forum.Description
            });
            var model = new ForumIndexModel
            {
                ForumList = forums
            };
            return View(model);
        }

        public ActionResult Topic(int id)
        {
            Forum forum = _forumService.GetById(id);
            IEnumerable<Post> posts = forum.Posts;

            var postListings = posts.Select(x => new PostListingModel
            {
                Id = x.Id,
                AuthorId = x.User.Id,
                AuthorRating = x.User.Rating,
                AuthorName = x.User.UserName,
                Title = x.Title,
                DatePosted = x.Created.ToString(),
                RepliesCount = x.Replies.Count(),
                Forum = BuildForumListing(x)
            });

            var model = new ForumTopicModel
            {
                Posts = postListings,
                Forum = BuildForumListing(forum)
            };
            return View(model);
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;
            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Name = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }
    }
}

CELForum/CELForum/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CELForum.Data;
using CELForum.Data.Models;
using CELForum.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CELForum.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IApplicationUser _userService;
        private readonly IUpload _uploadService;
        public ProfileController(UserManager<ApplicationUser> userManager, IApplicationUser userService, IUpload uploadService)
        {
            _userManager = userManager;
            _userService = userService;
            _uploadService = uploadService;
        }

        public IActionResult Detail(string id)
        {
            var user = _userService.GetById(id);
            var userRoles = _userManager.GetRolesAsync(user).Result;
            var model = new ProfileModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                UserRating = user.Rating.ToString(),
                Email = user.Email,
                ProfileImageUrl = user.ProfileImageUrl,
                MemberSince = user.MemberSince,
                IsAdmin = userRoles.Contains("Admin")
            };
            return View(model);
        }
    }
}

CELForum/CELForum/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CELForum.Data;
using CELForum.Data.Models;
using CELForum.Models;
using Microsoft.AspNetCore.Mvc;

namespace CELForum.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPost _postService;

        public SearchController(IPost postService)
        {
            _postService = postService;
        }

        public IActionResult Results(string searchQuery)
        {
            var post = _postService.GetFilteredPosts(searchQuery);
            var areNoResults = (!string.IsNullOrEmpty(searchQuery) && !post.Any());
            var postListings = post.Select(x => new PostListingModel
            {
                Id = x.Id,
                AuthorId = x.User.Id,
                AuthorRating = x.User.Rating,
                AuthorName = x.User.UserName,
                Title = x.Title,
                DatePosted = x.Created.ToString(),
                RepliesCount = x.Replies.Count(),
                Forum = BuildForumListing(x)
            });
            var model = new SearchResultModel
            {
                Posts = postListings,
                SearchQuery = searchQuery,
                EmptySearchResults = areNoResults
            };
            return View(model);
        }
        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;
            return BuildForumListing(forum);
        }
        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Name = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }

        [HttpPost]
        public IActionResult Search(string searchQuery)
        {
            return RedirectToAction("Results", new { searchQuery });
        }
    }
}

CELForum/CELForum/Views/Search/Results.cshtml
@model CELForum.Models.SearchResultModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Topic</title>
</head>
<body>
    <div class="container body-content">
        <div class="row sectionHeader">
            <div class="sectionHeading">
                <span>Search Results for : @Model.SearchQuery</span>
                
                <form asp-controller="Search" asp-action="Search" method="post">
                    <div class="searchForm">
                        <input asp-for="SearchQuery" type="text" placeholder="Search..." class="searchBar" onfocus="clearThis(this)" />
                        <button type="submit" class="btn btn-forumSearch">
                            <i class="material-icons">search</i>
                        </button>
                    </div>
                </form>
            </div>            
        </div>
        <div class="row forumIndexContent">
            @if (!Model.EmptySearchResults)
            {
                <table class="table table-hover table-bordered" id="forumIndexTable">
                    <tbody>
                        @foreach (var post in Model.Posts)
                        {
                            <tr>
                                <td>                                    
                                    <div class="postData">
                                        <div class="postTitle">
                                            <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">@post.Title</a>
                                        </div>
                                        <div class="forumSubTitle">
                                            <div>
                                                by :
                                                <span class="postAuthor">
                                                    <a asp-controller="Profile" asp-action="Detail" asp-route-id="@post.AuthorId">
                                                        @post.AuthorName
                                                    </a>
                                                    (@post.AuthorRating)
                                                </span>                                                
                                                in :
                                                <span class="postForum">
                                                    <a asp-controller="Forum" asp-action="Topic" asp-route-id="@post.Forum.Id">
                                                        @post.Forum.Name
                                                    </a>
                                                </span>
                                                on :
                                                <span class="postDate">
                                                    @post.DatePosted
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="forumPostCount">
                                        Replies : @post.RepliesCount
                                    </div>
                                </td>
                                <td>
                                    <div class="postDate">
                                        @post.DatePosted
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="noPosts">
                    <i class="material-icons md-72">question_answer</i>
                    <h3>
                        No search result found for @Model.SearchQuery<br />
                    </h3>
                </div>
            }
        </div>
    </div>
</body>
</html>

@section Scripts
    {
    <script>
        function clearThis(target) {
            target.value = "";
        }
    </script>
}